name: Docker Publish E2E Hardhat

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image tag (default: latest)'
        required: false
        default: "latest"
      contract_version:
        description: 'Contracts version (example: v0.4.4), checkout at price-oracle-dvs'
        required: true

jobs:
  build_and_publish:
    name: Build
    runs-on: ["self-hosted", "Linux", "X64", "ci"]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker Tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./test/e2e
          file: ./docker/contracts/Dockerfile
          push: true
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
            CONTRACT_VERSION=${{ github.event.inputs.contract_version }}
          tags: |
            pellnetwork/pell-emulator-e2e-hardhat:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            github_token=${{ secrets.GH_TOKEN }}
